services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: riccardorubini
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ocrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
      - ollama
    environment:
      POSTGRES_URL: postgresql+asyncpg://riccardorubini:yourpassword@db:5432/ocrdb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      #OLLAMA_URL: http://ollama:11434
      OLLAMA_URL: http://host.docker.internal:11434
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    ports:
      - "3003:3003"
    working_dir: /app
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data: 